version: '3.8'

services:
  nazuna-panel:
    build: .
    container_name: nazuna-panel
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./nazuna:/app/nazuna
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/nazuna.db
    networks:
      - nazuna-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: nazuna-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - nazuna-network

  nginx:
    image: nginx:alpine
    container_name: nazuna-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nazuna-panel
    networks:
      - nazuna-network

volumes:
  redis_data:

networks:
  nazuna-network:
    driver: bridge

